name = str(input('WHATS YOUR NAME ?  '))
print("Hello" ,(name))
gen = str(input('WHATS YOUR gender ?  '))
print("So you are a " ,(gen))
dobd= int(input('WHATS YOUR Birth date ?  '))
print("OK So day of your birth is  ",  (dobd))
dobm= int(input('WHATS YOUR Birth Month ?  '))
print("OK So month of your birth is  ",  (dobm))
doby= int(input('WHATS YOUR Birth year ?  '))
print("OK So year of your birth is  ",  (doby))
fname = str(input('WHATS YOUR  FATHERS NAME ?  '))
print("OK SO YOUR FATHER IS", (fname))
mname = str(input('WHATS YOUR  MOTHERS NAME ?  '))
print("OK SO YOUR MOTHER IS", (mname) )
prof = str(input('WHATS YOUR PROFESSION ?  '))
print("OKAY .. SO YOU ARE A ",  (prof))
resp = str(input("Do you want to print the biodata ? "))
print("Gathering all the data ---------------------------------------------------")
print("Combining data please wait ................................................")
print("Please wait while we prepare your profile and update your personal information and data .................")
print("................................................................................................................")
print("................................................................................................................")
print("................................................................................................................")
print("................................................................................................................")
print("*****************************************************")
print("*****************************************************")
print ("YOUR BIODATA  -  ")
print("NAME - ", (name))
print("Date of birth  - ", (dobd), "-",(dobm), "-", (doby))
print("Gender - ", (gen))
print("PROFESSION - ", (prof))
print("FATHERS NAME -", (fname))
print("MOTHERS NAME - ", (mname))
print("Thanks for using the biodata printer")






